spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_ai
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false

bank-ai:
  vllm:
    embedding:
      url: http://ec2-3-76-225-90.eu-central-1.compute.amazonaws.com:8001/v1
      model: Qwen/Qwen3-Embedding-0.6B
    chat:
      url: http://ec2-3-76-225-90.eu-central-1.compute.amazonaws.com:8000/v1
      model: Qwen/Qwen3-0.6B
